// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

type User struct {
	ID       int32
	Username string
	Name     string
	Surname  string
	Email    string
	Password string
}
